#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0 -d I II III IV w e r z x
# bspc monitor eDP1 -d I

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a krita desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a firefox desktop='^1'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a Kodi desktop='^5'

xsetroot -cursor_name left_ptr
# Disable screen sleep
xset -dpms
xset s off

xfce4-session &
compton -b
GAZE_LOG_FILE_DIR=$HOME/.gaze gazed -D
firefox &
google-chrome &
# kodi &
