#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP1 -d I II III IV q w e r z x
bspc monitor eDP1 -d I

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a krita desktop='^8' state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --auto --output HDMI2 --primary --mode 1920x1080 --left-of eDP1

polybar -c /home/kick/.config/polybar/config main &
polybar -c /home/kick/.config/polybar/config laptop &
xsetroot -cursor_name left_ptr
/scripts/52-background-image.sh &

xfce4-session &
picom &
unclutter &
