#!/bin/sh

notify-send.sh 'TRIM in progress' --icon=dialog-information

result=`fstrim -v /`

notify-send.sh 'TRIM Complete!' "$result" --icon=dialog-information
echo $result'\n'`date`' TRIM has executed' >> /var/log/fstrim.log
